//abilities
export const medQOne = [
  "overgrow",
  "blaze",
  "torrent",
  "shed skin",
  "keen eye",
  "run away",
  "intimidate",
  "static",
  "sand veil",
  "poison point",
  "cute charm",
  "flash fire",
  "inner focus",
  "chlorophyll",
  "effect spore",
  "shield dust",
  "limber",
  "damp",
  "vital spirit",
  "water absorb",
  "synchronize",
  "guts",
  "clear body",
  "run away",
  "oblivious",
  "magnet pull",
  "thick fat",
  "stench",
  "shell armor",
  "levitate",
  "insomnia",
  "hyper cutter",
  "soundproof",
  "rock head",
  "lightning rod",
  "swift swim",
  "illuminate",
  "",
];

//evolves from

export const medQTwo = [
  "nidoran-m",
  "bulbasaur",
  "charmander",
  "squirtle",
  "caterpie",
  "weedle",
  "pidgey",
  "rattata",
  "spearow",
  "ekans",
  "pikachu",
  "sandshrew",
  "nidoran-f",
  "clefiary",
  "vulpix",
  "jigglypuff",
  "zubat",
  "oddish",
  "paras",
  "venonat",
  "diglett",
  "meowth",
  "psyduck",
  "mankey",
  "growlithe",
  "poliwag",
  "abra",
  "machop",
  "bellsprout",
  "tentacool",
  "geodude",
  "ponyta",
  "slowpoke",
  "magnemite",
  "doduo",
  "seel",
  "grimer",
  "shelder",
  "gastly",
  "drowzee",
  "krabby",
  "voltorb",
  "exeggcute",
  "cubone",
  "koffing",
  "rythorn",
  "horsea",
  "goldeen",
  "staryu",
  "magikarp",
  "omanyte",
  "kabuto",
  "dratini",
];

//evolves to
export const medQThree = [
  "venusaur",
  "charizard",
  "blastoise",
  "butterfree",
  "beedrill",
  "pidgeot",
  "nidoqueen",
  "nidoking",
  "vileplume",
  "poliwrath",
  "alakazam",
  "machamp",
  "victreebell",
  "golem",
  "gengar",
  "hitmonlee",
  "hitmonchan",
  "lapras",
  "eevee",
  "vaporeon",
  "jolteon",
  "flareon",
  "aerodactyl",
  "snorlax",
  "articuno",
  "zapdos",
  "moltres",
  "dragonite",
  "mewtwo",
  "mew",
  "doesn't evolve",
];

export const medPokemon = [
  {
    id: 2,
    name: "ivysaur",
    abilities: "overgrow",
    evolvesFrom: "bulbasaur",
    evolvesTo: "venusaur",
  },
  {
    id: 5,
    name: "charmeleon",
    abilities: "blaze",
    evolvesFrom: "charmander",
    evolvesTo: "charizard",
  },
  {
    id: 8,
    name: "wartotle",
    abilities: "torrent",
    evolvesFrom: "squirtle",
    evolvesTo: "blastoise",
  },
  {
    id: 11,
    name: "metapod",
    abilities: "shed skin",
    evolvesFrom: "caterpie",
    evolvesTo: "butterfree",
  },
  {
    id: 14,
    name: "Kakuna",
    abilities: " shed skin",
    evolvesFrom: "weedle",
    evolvesTo: "beedrill",
  },
  {
    id: 17,
    name: "pideotto",
    abilities: "keen eye",
    evolvesFrom: "pidgey",
    evolvesTo: "pidgeot",
  },
  {
    id: 20,
    name: "raticate",
    abilities: "run away",
    evolvesFrom: "rattata",
    evolvesTo: "",
  },
  {
    id: 22,
    name: "fearow",
    abilities: "keen eye",
    evolvesFrom: "spearow",
    evolvesTo: "",
  },
  {
    id: 24,
    name: "arbok",
    abilities: "intimidate",
    evolvesFrom: "ekans",
    evolvesTo: "",
  },
  {
    id: 26,
    name: "raichu",
    abilities: "static",
    evolvesFrom: "pikachu",
    evolvesTo: "",
  },
  {
    id: 28,
    name: "sandslash",
    abilities: "sand veil",
    evolvesFrom: "sandshrew",
    evolvesTo: "",
  },
  {
    id: 30,
    name: "nidorina",
    abilities: "poison point",
    evolvesFrom: "nidoran-f",
    evolvesTo: "nidoqueen",
  },
  {
    id: 33,
    name: "nidorino",
    abilities: "poison point",
    evolvesFrom: "nidoran-m",
    evolvesTo: "nidoking",
  },
  {
    id: 36,
    name: "clefable",
    abilities: "cute charm",
    evolvesFrom: "clefairy",
    evolvesTo: "",
  },
  {
    id: 38,
    name: "ninetales",
    abilities: "flash fire",
    evolvesFrom: "vulpix",
    evolvesTo: "",
  },
  {
    id: 40,
    name: "wigglytuff",
    abilities: "cute charm",
    evolvesFrom: "jigglypuff",
    evolvesTo: "",
  },
  {
    id: 42,
    name: "golbat",
    abilities: "inner focus",
    evolvesFrom: "zubat",
    evolvesTo: "",
  },
  {
    id: 44,
    name: "gloom",
    abilities: "chlorophyll",
    evolvesFrom: "oddish",
    evolvesTo: "vileplume",
  },
  {
    id: 47,
    name: "parasect",
    abilities: "effect spore",
    evolvesFrom: "paras",
    evolvesTo: "",
  },
  {
    id: 49,
    name: "venomoth",
    abilities: "shield dust",
    evolvesFrom: "venonant",
    evolvesTo: "",
  },
  {
    id: 51,
    name: "dugtrio",
    abilities: "sand veil",
    evolvesFrom: "diglett",
    evolvesTo: "",
  },
  {
    id: 53,
    name: "persian",
    abilities: "limber",
    evolvesFrom: "meowth",
    evolvesTo: "",
  },
  {
    id: 55,
    name: "golduck",
    abilities: "damp",
    evolvesFrom: "psyduck",
    evolvesTo: "",
  },
  {
    id: 57,
    name: "primeape",
    abilities: "vital spirit",
    evolvesFrom: "mankey",
    evolvesTo: "",
  },
  {
    id: 59,
    name: "arcanine",
    abilities: "intimidate",
    evolvesFrom: "growlithe",
    evolvesTo: "",
  },
  {
    id: 61,
    name: "poliwhirl",
    abilities: "water absorb",
    evolvesFrom: "poliwhirl",
    evolvesTo: "poliwrath",
  },
  {
    id: 64,
    name: "kadabra",
    abilities: "synchronize",
    evolvesFrom: "abra",
    evolvesTo: "alakazam",
  },
  {
    id: 67,
    name: "machoke",
    abilities: "guts",
    evolvesFrom: "machop",
    evolvesTo: "machamp",
  },
  {
    id: 70,
    name: "weepinbell",
    abilities: "chlorophyll",
    evolvesFrom: "bellsprout",
    evolvesTo: "victreebel",
  },
  {
    id: 73,
    name: "tentacruel",
    abilities: "clear body",
    evolvesFrom: "tentacool",
    evolvesTo: "",
  },
  {
    id: 75,
    name: "graveler",
    abilities: " rock head",
    evolvesFrom: "geodude",
    evolvesTo: "golem",
  },
  {
    id: 78,
    name: "rapidash",
    abilities: "run away",
    evolvesFrom: "ponyta",
    evolvesTo: "",
  },
  {
    id: 80,
    name: "slowbro",
    abilities: "oblivious",
    evolvesFrom: "slowpoke",
    evolvesTo: "",
  },
  {
    id: 82,
    name: "magneton",
    abilities: "magnet pull",
    evolvesFrom: "magnemite",
    evolvesTo: "",
  },
  {
    id: 85,
    name: "dodrio",
    abilities: "run away",
    evolvesFrom: "doduo",
    evolvesTo: "",
  },
  {
    id: 87,
    name: "dewgong",
    abilities: "thick fat",
    evolvesFrom: "seel",
    evolvesTo: "",
  },
  {
    id: 89,
    name: "muk",
    abilities: "stench",
    evolvesFrom: "grimer",
    evolvesTo: "",
  },
  {
    id: 91,
    name: "cloyster",
    abilities: "shell armor",
    evolvesFrom: "shellder",
    evolvesTo: "",
  },
  {
    id: 93,
    name: "haunter",
    abilities: "levitate",
    evolvesFrom: "gastly",
    evolvesTo: "gengar",
  },
  {
    id: 97,
    name: "hypno",
    abilities: "insomnia",
    evolvesFrom: "drowzee",
    evolvesTo: "",
  },
  {
    id: 99,
    name: "kingler",
    abilities: "hyper cutter",
    evolvesFrom: "krabby",
    evolvesTo: "",
  },
  {
    id: 101,
    name: "electrode",
    abilities: "soundproof",
    evolvesFrom: "voltorb",
    evolvesTo: "",
  },
  {
    id: 103,
    name: "exeggutor",
    abilities: "chlorophyll",
    evolvesFrom: "exeggcute",
    evolvesTo: "",
  },
  {
    id: 105,
    name: "marowak",
    abilities: "rock hard",
    evolvesFrom: "",
    evolvesTo: "",
  },
  {
    id: 110,
    name: "weezing",
    abilities: "levitate",
    evolvesFrom: "koffing",
    evolvesTo: "",
  },
  {
    id: 112,
    name: "rhydon",
    abilities: "lightning rod",
    evolvesFrom: "rhyhorn",
    evolvesTo: "",
  },
  {
    id: 117,
    name: "seadra",
    abilities: "poison point",
    evolvesFrom: "horsea",
    evolvesTo: "",
  },
  {
    id: 119,
    name: "seaking",
    abilities: "swift swim",
    evolvesFrom: "goldeen",
    evolvesTo: "",
  },
  {
    id: 121,
    name: "starmie",
    abilities: "natural cure",
    evolvesFrom: "staryu",
    evolvesTo: "",
  },
  {
    id: 130,
    name: "gyarados",
    abilities: "intimidate",
    evolvesFrom: "magikarp",
    evolvesTo: "",
  },
  {
    id: 139,
    name: "omastar",
    abilities: "swift swim",
    evolvesFrom: "omanyte",
    evolvesTo: "",
  },
  {
    id: 141,
    name: "kabutops",
    abilities: "swift swim",
    evolvesFrom: "kabuto",
    evolvesTo: "",
  },
  {
    id: 148,
    name: "dragonair",
    abilities: "shed skin",
    evolvesFrom: "dratini",
    evolvesTo: "dragonite",
  },
];
